### ISSUE TITLE
maintenance team?

### ISSUE THREAD

**Issue by anarcat** [gurgeh/selfspy#161]
hi!

could it be possible to add people that can approve pull requests and make releases here? looking at that [twitter discussion](https://twitter.com/waldyrious/status/905797468985712640) and the feedback I received on https://github.com/gurgeh/selfspy/pull/156#issuecomment-327815196 from @waldyrious, it looks like you'd be open to adding more admins or moving to a separate organization.

at least, before you go, you should share access to the PyPI project because *that* is a pain to recover if you abandon the project.

thanks!

**Comment by anarcat** [comment]
pinged @gurgeh again on twitter here: https://twitter.com/theanarcat/status/929841791427383296

**Comment by anarcat** [comment]
FWIW, i have created an organization named `selfspy` and invited @gurgeh there. next step is to move the project there so we can collaboratively review and merge PRs.

**Comment by gurgeh** [comment]
This seems like a good idea

**Comment by gurgeh** [comment]
@anarcat I see no invitation to the "selfspy" organization. What do I have to do to help you move the project there?

**Comment by waldyrious** [comment]
I'd suggest making all members of the organization public, by the way, to make it more visible who are the people that contributors can reach out to, in case repo activity or response times happen to slow down again.

**Comment by anarcat** [comment]
@gurgeh i'm not sure - i invited you there, and renewed the invitation just now. can't you see a link in your inbox or something?

the organization is here: https://github.com/selfspy

@waldyrious I made my membership public - it looks like it's a per-member thing.

**Comment by gurgeh** [comment]
OK, so now the "selfspy" organization owns the repo!

BTW, the invitation did not turn up in my inbox, but when I clicked the organization link above, I could join.

**Comment by anarcat** [comment]
excellent, good job!

**Comment by giansegato** [comment]
Hi @anarcat, @gurgeh! I've seen that this project went idle for quite some time again (the last commit is dated more than 3 years ago). I believe there are a few major maintenance fixes that should be brought forward (eg. breaking pyobjc incompatibilities with the latest cocoa releases, a needed transition from Python 2 to Python 3.x, since 2.7 will be discontinued, etc.)

I would be interested in moving the project forward since I can see a lot of value in it. Any chance: 
1. that some of the current administrator(s) are willing to approve pull requests again?
2. and/or: that it will be possible to be included in the admins group?

Thanks!
